ktor:
    deployment:
        port: 8085
        callGroupSize: 8
        connectionGroupSize: 4
        workerGroupSize: 4
    application:
        modules:
            - coliver.ApplicationKt.module


storage:
    user: $USER
    password: $PASSWORD
    jdbcURL: $JDBC_URL
