ktor:
    deployment:
        port: 8085
        connectionGroupSize: 4
        workerGroupSize: 4
        callGroupSize: 8
    application:
        modules:
            - coliver.ApplicationKt.module


storage:
    user: "postgres"
    password: "B7Q4zAjtiadRyT"
    jdbcURL: "jdbc:postgresql://94.103.89.23:5432/coliver"


jwt:
    secret: "secret"
    issuer: "coliver.tech"
    audience: "user"
    realm:  "Access to 'page'"
